name: ip
author: terrier989 <terrier989@gmail.com>
homepage: https://github.com/gohilla/dart-ip
description: A package for working with the IP protocol stack (IPv4, IPv6, ICMP, TCP, UDP).

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  raw:
    git: git@github.com:tomialagbe/raw.git

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8